development:
  adapter: postgresql
  database: toppleit_dev
  username: anthonybui
  password: 
  host: localhost

test:
  adapter: postgresql
  database: toppleit_test
  username: anthonybui
  password: 
  host: localhost

production:
  adapter: postgresql
  database: toppleit
  username: root
  password: root
  host: localhost